const dappMnemonic = 'era message genuine crystal margin cricket fabric address tank omit swing large';
const dappIdentityId = 'HK1jnhxWMDuoEwkvKXTXFR5WeTYzx4Vm9C7Yx9qPhWXC';
const dappUsername = 'dappuser'
const dappAddress = 'yMxELPfsPbn5UienyykyySLJ4TA3QQCqw5'
const messageContractId = '3coTShwTvmKiySpwmDDzRJ9FGQx4RNLdawLttT9RNxXa';
const dpnsContractID = '36ez8VqoDbR8NkdXwFaf9Tp8ukBdQxN8eYs8JNMnUyKz';
const dashNetwork = 'testnet';
const evalToken = 'DY6KmhAsLqrkTxJWA7KAJA3vR4wHhExHqSYXLWitdxuu';
const funToken = 'AvDumErCNn5Z6dgpDbBNemwyHLudFyyBgAiU1B5QrEMe';
